from abc import ABC, abstractmethod

class LLMClient(ABC):

    """Interface for language model clients."""

    @abstractmethod
    def generate_response(self, system_prompt: str, user_prompt: str) -> str:

        """
        Generate a response from the LLM based on system and user prompts.

        :param system_prompt: The system prompt that sets the context and behavior for the model.
        :param user_prompt: The user prompt that contains the actual request or question.

        :return: A response string generated by the LLM.

        """

        pass


if __name__ == "__main__":
    pass
